### ISSUE TITLE
Save current background doesn't work

### ISSUE THREAD

**Issue by maj127** [Simonmicro/better-backgrounds#18]
Linux Mint 20.3 Cinnamon
Cinnamon Version 5.2.7
Linux Kernal 5.4.0-100-generic

Save background feature isn't working at all

https://user-images.githubusercontent.com/46169477/160256178-88266cf1-4c3c-4a78-930c-183f6182f589.mp4

!

**Comment by simonmicro** [comment]
Oh, thats very unfortunate! Could you take a look at Looking Glass and see if any exceptions pop up? By default you just have to hit "Super+L"... Sadly everything works fine for me, so... Do you forgot to install `imagemagick`?

**Comment by simonmicro** [comment]
Just tried it - and it works. Please provide more information, as I otherwise have to consider this issue as closed.

**Comment by simonmicro** [comment]
Seems like other users had this issue too. With the newest update 5e194483af4c0657c4627d4c18d2e15886e77b74 a warning will be displayed.

**Comment by DRR0B0T** [comment]
It doesn't work, Linux Mint Cinamon, App crashed with warning external error 503 can't download from unsplash.

**Comment by DRR0B0T** [comment]
Exactly the same error as in the video
