### ISSUE TITLE
Feature request: Enable/Disable panel transparency 

### ISSUE THREAD

**Issue by TopperBG** [Simonmicro/better-backgrounds#21]
To be able switch on/off panel transparency will be good as feature.

**Comment by simonmicro** [comment]
So, you want the functions of https://cinnamon-spices.linuxmint.com/extensions/view/81?

**Comment by TopperBG** [comment]
Nope, I want to be switchable. Let me describe: I hate transparant panels cause the tabs there visualize some info from running apps. And I've setup all panels solid color. But when is active Better-Backgrounds on every reload, all panels that I have became transparant. So I suggest that behaviour to be an option with on/off.

**Comment by simonmicro** [comment]
This sounds more like a bug to me. So you mean every time this applet is loading (so the icon is animated) your panels turn transparent? In that case it seems to be a bug with Cinnamon, as I have none such feature. Does this bug still occur if you disable the applet animations?

![image](https://user-images.githubusercontent.com/24966116/189872080-0f3373b4-9cdb-4816-a9fb-8f77b5691777.png)

**Comment by TopperBG** [comment]
Could be Cinnamon bug, cause when switch to original Cinnamon or CBlack that effect doesn't happened. 12 other themes turn on transparent panels if BB applet is in it. Animated icon doesn't change anything.

**Comment by simonmicro** [comment]
Please open a bug in the Cinnamon repos, as this applet is not responsible (knowingly) for this "feature". I think the Cinnamon devs maybe broke something with newer versions... Sorry.
